server:
  port: 8502

spring:
  applicaction:
    name: account-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    enabled: true



accountservice:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: accountservice

    username: cassandra
    password: cassandra